CREATE TABLE IF NOT EXISTS subject_replacement_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    task_name VARCHAR(100),
    original_video_url VARCHAR(1024) NOT NULL,
    output_video_url VARCHAR(1024),
    thumbnail_url VARCHAR(1024),
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    aspect_ratio VARCHAR(10) DEFAULT '16:9',
    duration INT DEFAULT 5,
    generate_audio TINYINT(1) DEFAULT 1,
    watermark TINYINT(1) DEFAULT 0,
    model VARCHAR(100),
    prompt TEXT,
    replacements_json TEXT,
    volcengine_task_id VARCHAR(100),
    error_message TEXT,
    submitted_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    generation_duration INT,
    seed BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_subject_replacement_user_created (user_id, created_at),
    INDEX idx_subject_replacement_status (status)
);
